ClothesWeb/Models/Cart.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ClothesWeb.Models
{
  public class Cart
  {
    [Key]
    public int Id { get; set; }

    public int ProductId { get; set; }

    [ForeignKey("ProductId")]
    [ValidateNever]
    public Product Product { get; set; }

    public int Quantity { get; set; }
    public string? Size { get; set; }

    public bool isCheckout { get; set; }

    [NotMapped]
    public double ProductPrice { get; set; }

    public string ApplicationUserId { get; set; }

    [ForeignKey("ApplicationUserId")]
    [ValidateNever]
    public ApplicationUser ApplicationUser { get; set; }
  }
}

ClothesWeb/Models/CartViewModel.cs
namespace ClothesWeb.Models
{
  public class CartViewModel
  {
    public IEnumerable<Cart> listCart { get; set; }
    public HoaDon HoaDon { get; set; }
    public Product Product { get; set; }
    public ApplicationUser User { get; set; }

    public IEnumerable<ChiTietHoaDon> listChiTiet { get; set; }
    public ChiTietHoaDon ChiTietHoaDon { get; set; }
  }
}

ClothesWeb/Areas/Customer/Controllers/CartController.cs
using ClothesWeb.Data;
using ClothesWeb.Helpers;
using ClothesWeb.Migrations;
using ClothesWeb.Models;
using ClothesWeb.Models.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.ComponentModel;
using System.Security.Claims;

namespace ClothesWeb.Areas.Customer.Controllers
{
  [Area("Customer")]
  [Authorize]
  public class CartController : Controller
  {
    private readonly ApplicationDbContext _db;
    private readonly IVnPayService _vnPayService;

    public CartController(ApplicationDbContext db, IVnPayService vnPayService)
    {
      _db = db;
      _vnPayService = vnPayService;
    }

    public List<Cart> Cart = new List<Cart>();
    double totalPrice = 0;

    public IActionResult Index()
    {
      //Get Infor of Account
      var identity = (ClaimsIdentity)User.Identity;
      var claim = identity.FindFirst(ClaimTypes.NameIdentifier);

      //Get List of Product in Cart of User
      CartViewModel cart = new CartViewModel()
      {
        listCart = _db.Carts
        .Include("Product")
        .Where(x => x.ApplicationUserId == claim.Value).ToList(),
        HoaDon = new HoaDon()
      };

      foreach (var item in cart.listCart)
      {
        if (item.isCheckout == false)
        {
          return RedirectToAction("NoProductPage");

        }
        else
        {
          //Pay by product quantity.
          item.ProductPrice = item.Quantity * item.Product.Price;

          //Check out the shopping cart.
          totalPrice += item.ProductPrice;
          ViewBag.SubTotal = totalPrice;
          cart.HoaDon.TotalPrice = totalPrice + 32000;
        }
      }


      if (cart.listCart.Count() == 0)
      {
        return RedirectToAction("NoProductPage");
      }

      return View(cart);
    }

    [HttpGet]
    public IActionResult ThanhToan()
    {
      //Get Infor of Account
      var identity = (ClaimsIdentity)User.Identity;
      var claim = identity.FindFirst(ClaimTypes.NameIdentifier);

      //Get List of Product in Cart of User
      CartViewModel cart = new CartViewModel()
      {
        listCart = _db.Carts
        .Include("Product")
        .Where(x => x.ApplicationUserId == claim.Value).ToList(),
        HoaDon = new HoaDon()
      };

      foreach (var item in cart.listCart)
      {
        // SL * Gia
        item.ProductPrice = item.Quantity * item.Product.Price;
        //Check out the shopping cart.
        totalPrice += item.ProductPrice;
      }
      cart.HoaDon.TotalPrice = totalPrice + 32000;

      cart.HoaDon.User = _db.ApplicationUser.FirstOrDefault(user => user.Id == claim.Value);
      cart.HoaDon.Name = cart.HoaDon.User.Name;
      cart.HoaDon.Address = cart.HoaDon.User.Address;
      cart.HoaDon.PhoneNumber = cart.HoaDon.User.PhoneNumber;

      return View(cart);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ThanhToan(CartViewModel cart, string payment = "COD")
    {
      //Get Infor of Account
      var identity = (ClaimsIdentity)User.Identity;
      var claim = identity.FindFirst(ClaimTypes.NameIdentifier);

      // Tim id KH trong table Cart
      cart.listCart = _db.Carts
        .Include("Product")
          .Where(cart => cart.ApplicationUserId == claim.Value)
          .ToList();

      // Dem sp trong Cart
      if (cart.listCart.Count() == 0)
      {
        TempData["EmptyCartMessage"] = "Chưa có sản phẩm trong giỏ hàng.";
        return RedirectToAction("Index", "Home");
      }

      // Chon phuong thuc thanh toan va thanh toan
      if (payment == "Thanh toán VNPay")
      {
        var vnPaymentModel = new VnPaymentRequestModel();
        foreach (var item in cart.listCart)
        {
          item.ProductPrice = item.Quantity * item.Product.Price;
          vnPaymentModel.Amount += item.ProductPrice;
        }
        vnPaymentModel.CreatedDate = DateTime.Now;
        vnPaymentModel.Amount += 32000;
        vnPaymentModel.OrderId = new Random().Next(1000, 100000);

        return Redirect(_vnPayService.CreatePaymentUrl(HttpContext, vnPaymentModel));
      }

      cart.HoaDon.ApplicationUserId = claim.Value; // Lay id KH gans = id KH vao HoaDon
      cart.HoaDon.OrderStatus = "Đang xác nhận"; // Trang thai cho xac nhan
      cart.HoaDon.OrderDate = DateTime.Now; // Thoi gian hien tại
      cart.HoaDon.GhiChu = cart.HoaDon.GhiChu; // Ghi chu
      cart.HoaDon.PayMentMethod = payment; // PT thanh toan
      cart.HoaDon.ShippingUnit = "LiliExpress"; // Cứng
      cart.HoaDon.ShippingCost = 32000; // Cứng

      foreach (var item in cart.listCart)
      {
        // Số lượng * Giá SP
        item.ProductPrice = item.Quantity * item.Product.Price;
        // Sum
        //cart.HoaDon.TotalPrice += item.ProductPrice;
        totalPrice += item.ProductPrice;
      }
      // Cộng thêm tiền vận chuyển
      totalPrice += 32000;

      // Lưu tổng tiền vào cart.HoaDon.TotalPrice
      cart.HoaDon.TotalPrice = totalPrice;

      _db.Database.BeginTransaction();
      try
      {
        _db.HoaDons.Add(cart.HoaDon);
        _db.SaveChanges();

        foreach (var item in cart.listCart)
        {
          ChiTietHoaDon chiTietHoaDon = new ChiTietHoaDon()
          {
            ProductId = item.ProductId,
            HoaDonId = cart.HoaDon.Id,
            Username = cart.HoaDon.Name,
            ProductName = item.Product.Name,
            ProductPrice = item.ProductPrice,
            Quantity = item.Quantity,
            ImgURL = item.Product.ImageUrl,
          };
          _db.ChiTietHoaDons.Add(chiTietHoaDon);
          _db.Carts.RemoveRange(cart.listCart);
          _db.SaveChanges();
          _db.Database.CommitTransaction();

          return RedirectToAction("PaymentSuccess");
        }
      }
      catch (Exception ex)
      {
        _db.Database.RollbackTransaction();
      }
      //_db.SaveChanges();
      return View(cart);
    }

    // Xoa sp khoi Gio Hang
    public IActionResult DeleteProduct(int cartId)
    {
      var cartItem = _db.Carts.FirstOrDefault(x => x.Id == cartId);

      _db.Carts.Remove(cartItem);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // Giam so luong san pham
    public IActionResult Giam(int cartId)
    {
      var cart = _db.Carts.FirstOrDefault(cart => cart.Id == cartId);
      cart.Quantity -= 1;

      if (cart.Quantity == 0)
      {
        _db.Carts.Remove(cart);
      }
      _db.SaveChanges();

      return RedirectToAction("Index");
    }

    // Tang so luong san pham
    public IActionResult Tang(int cartId)
    {
      var cart = _db.Carts.FirstOrDefault(cart => cart.Id == cartId);
      cart.Quantity += 1;
      _db.SaveChanges();

      return RedirectToAction("Index");
    }

    // Khong co sp trong Gio Hang Redirect 
    public IActionResult NoProductPage()
    {
      return View();
    }

    public IActionResult PaymentFail()
    {
      return View();
    }

    public IActionResult PaymentSuccess()
    {
      return View();
    }

    public IActionResult PaymentCallBack()
    {
      var response = _vnPayService.PaymentExecute(Request.Query);

      if (response == null || response.VnPayResponseCode != "00")
      {
        TempData["Message"] = $"Lỗi thanh toán VNPay: {response.VnPayResponseCode}";
        return RedirectToAction("PaymentFail");
      }

      // Success: Lưu đơn hàng vao DB
      
      TempData["Message"] = $"Thanh toán VNPay thành công";
      return RedirectToAction("PaymentSuccess");
    }
  }
}

ClothesWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ClothesWeb.Areas.Identity.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ReturnUrl { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string ErrorMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl ??= Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

ClothesWeb/Areas/Owner/Controllers/DonHangController.cs
using Azure;
using ClothesWeb.Data;
using ClothesWeb.Migrations;
using ClothesWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace ClothesWeb.Areas.Owner.Controllers
{
  [Area("Owner")]
  public class DonHangController : Controller
  {
    private readonly ApplicationDbContext _db;

    public DonHangController(ApplicationDbContext db)
    {
      _db = db;
    }

    public IActionResult Index(int page = 1)
    {
      IEnumerable<HoaDon> hoadons = _db.HoaDons.Include(x => x.User).OrderByDescending(x => x.OrderDate).ToList();
      const int pageSize = 12;
      page = page < 1 ? 1 : page;
      int recsCount = hoadons.Count();
      var pager = new Pager(recsCount, page, pageSize);
      int recSkip = (page - 1) * pageSize;
      var data = hoadons.Skip(recSkip).Take(pager.PageSize).ToList();
      this.ViewBag.Pager = pager;
      return View(data);
    }

    public IActionResult DonHangDetail(int donHangId)
    {
      var detailsOrder = _db.ChiTietHoaDons.
        Include(od => od.Product)
        .Where(od => od.HoaDonId == donHangId)
        .ToList();
      return View(_db.HoaDons.OrderByDescending(p => p.Id).ToList());
    }

    public IActionResult XacNhan(int donHangId)
    {
      var hoadon = _db.HoaDons.FirstOrDefault(x => x.Id == donHangId);
      if (hoadon != null)
      {
        hoadon.OrderStatus = "Đã xác nhận";
        _db.SaveChanges();
      }
      return View(hoadon);
    }

    public IActionResult DonhangDetailsAdmin(int id)
    {
      var chiTietHoaDonList = _db.ChiTietHoaDons
                                  .Include("HoaDon")
                                  .Where(chiTiet => chiTiet.HoaDonId == id)
                                  .ToList();

      var hoadon = _db.HoaDons.Where(x => x.Id == id).FirstOrDefault();
      if (hoadon != null)
      {
        ViewBag.Total = hoadon.TotalPrice;
        ViewBag.Name = hoadon.Name;
        ViewBag.Address = hoadon.Address;
        ViewBag.PhoneNumber = hoadon.PhoneNumber;
        ViewBag.GhiChu = hoadon.GhiChu;
        ViewBag.OrderStatus = hoadon.OrderStatus;
        if (chiTietHoaDonList.Any())
        {
          return View(chiTietHoaDonList);
        }
      }

      return NotFound();
    }

    public IActionResult DonhangDeleteAdmin(int id)
    {
      var donhangDelete = _db.HoaDons.FirstOrDefault(c => c.Id == id);
      if (donhangDelete == null)
      {
        return NotFound();
      }
      _db.HoaDons.Remove(donhangDelete);
      _db.SaveChanges();

      return RedirectToAction("Index");
    }
  }
}

ClothesWeb/ViewComponents/PhanLoaiViewComponent.cs
using ClothesWeb.Data;
using ClothesWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace ClothesWeb.ViewComponents
{
  public class PhanLoaiViewComponent : ViewComponent
  {
    private readonly ApplicationDbContext _db;

    public PhanLoaiViewComponent(ApplicationDbContext db)
    {
      _db = db;
    }

    public IViewComponentResult Invoke()
    {
      //Get products category
      IEnumerable<Category> cat = _db.Categories.ToList();
      return View(cat);
    }
  }
}

ClothesWeb/Areas/Customer/Views/Home/GetUserName.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@if (!SignInManager.IsSignedIn(User))
{
  <div class="favorit-items">
    <a class="nav-link" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #000; padding: 0;">
      Account
    </a>
  </div>
}
else
{
  <a id="manage" class="nav-link text-white" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @UserManager.GetUserName(User)</a>
}

ClothesWeb/Areas/Customer/Views/Home/Login.cshtml
<!-- slider Area Start-->
<div class="slider-area ">
  <!-- Mobile Menu -->
  <div class="single-slider slider-height2 d-flex align-items-center" data-background="~/assets/img/hero/category.jpg">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="hero-cap text-center">
            <h2>Login</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- slider Area End-->
<!--================login_part Area =================-->
<section class="login_part section_padding ">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 col-md-6">
        <div class="login_part_text text-center">
          <div class="login_part_text_iner">
            <h2>New to our Shop?</h2>
            <p>
              There are advances being made in science and technology
              everyday, and a good example of this is the
            </p>
            <a asp-controller="Home" asp-action="Sign_Up" class="btn_3">Create an Account</a>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="login_part_form">
          <div class="login_part_form_iner">
            <h3>
              Welcome! <br>
              Please Sign in now
            </h3>
            <form class="row contact_form" action="#" method="post" novalidate="novalidate">
              <div class="col-md-12 form-group p_star">
                <input type="text" class="form-control" id="name" name="name" value=""
                       placeholder="Username">
              </div>
              <div class="col-md-12 form-group p_star">
                <input type="password" class="form-control" id="password" name="password" value=""
                       placeholder="Password">
              </div>
              <div class="col-md-12 form-group">
                <div class="creat_account d-flex align-items-center">
                  <input type="checkbox" id="f-option" name="selector">
                  <label for="f-option">Remember me</label>
                </div>
                <button type="submit" value="submit" class="btn_3" asp-controller="Home" asp-action="Index">
                  log in
                </button>
                <a class="lost_pass" href="#">forget password?</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================login_part end =================-->

ClothesWeb/Areas/Customer/Views/Home/Product_List.cshtml
@using X.PagedList.Mvc.Core
@model IEnumerable<Product>

@{
  Pager pager = new Pager();
  int pageNo = 0;
  if (ViewBag.Pager != null)
  {
    pager = ViewBag.Pager;
    pageNo = pager.CurentPage;
  }
}

<div class="slider-area ">
  <!-- Mobile Menu -->
  <div class="single-slider slider-height2 d-flex align-items-center" data-background="~/assets/img/hero/category.jpg">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="hero-cap text-center">
            <h2>Danh sách sản phẩm</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- slider Area End-->
<!-- product list part start-->
<section class="product_list section_padding">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="product_sidebar">
          <div class="single_sedebar">
            @*<form action="#">
                <input type="text" name="#" placeholder="Search keyword">
                <i class="ti-search"></i>
              </form>*@
          </div>
          <div class="single_sedebar">
            <div class="select_option">
              <div class="select_option_list">Category <i class="right fas fa-caret-down"></i> </div>
              @await Component.InvokeAsync("PhanLoai")
            </div>
          </div>
        </div>
      </div>
      @* Lọc sản phẩm *@
      <div class="col-md-9">
        <span class="m-5 text-uppercase">Phân loại: @Model.FirstOrDefault()?.Category.Name</span>
        <hr />
        <div class="product_list d-flex flex-wrap">
          @foreach (var item in Model)
          {
            <div class="col-lg-6 col-md-6 col-sm-12 mb-4">
              <form asp-controller="Home" asp-action="Product_List" asp-route-loaiId="@item.LoaiId" method="get">
                <div class="single_product_item" style="width: 400px; height: 400px; object-fit: cover; text-align: center; align-items:center; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
                  <a asp-controller="Home" asp-action="Product_Details" asp-route-productId="@item.IdProduct">
                    <img src="@item.ImageUrl" alt="" class="img-thumbnail" style="width: 250px; height: 250px;object-fit: cover;">
                  </a>
                  <h3 style="font-size: 1rem; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; width: 100%; text-align: center; padding: 0 4px;">
                    <a asp-controller="Home" asp-action="Product_Details" asp-route-productId="@item.IdProduct">
                      @item.Name
                    </a>
                  </h3>

                  <p>@String.Format("{0:0,0}", @item.Price)đ</p>
                </div>
              </form>
            </div>
          }
        </div>

        <div class="container">
          @if (pager.TotalPages > 0)
          {
            <ul class="pagination justify-content-center">
              @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
              {
                <li class="page-item @(pge == pager.CurentPage ? "active" : "")">
                  <a class="page-link" asp-controller="Home" asp-route-loaiId="@ViewBag.LoaiId"
                     asp-action="Product_List"
                     asp-route-page="@pge">@pge</a>
                  </li>
                }
            </ul>
          }
        </div>
      </div>
    </div>
  </div>
</section>

<!-- product list part end-->
<!-- client review part here -->
<section class="client_review">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="client_review_slider owl-carousel">
          <div class="single_client_review">
            <div class="client_img">
              <img src="~/assets/img/client.png" alt="#">
            </div>
            <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering.</p>
            <h5>- Micky Mouse</h5>
          </div>
          <div class="single_client_review">
            <div class="client_img">
              <img src="~/assets/img/client_1.png" alt="#">
            </div>
            <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering.</p>
            <h5>- Micky Mouse</h5>
          </div>
          <div class="single_client_review">
            <div class="client_img">
              <img src="~/assets/img/client_2.png" alt="#">
            </div>
            <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering.</p>
            <h5>- Micky Mouse</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- client review part end -->
<!-- Shop Method Start-->
<div class="shop-method-area section-padding30">
  <div class="container">
    <div class="row d-flex justify-content-between">
      <div class="col-xl-3 col-lg-3 col-md-6">
        <div class="single-method mb-40">
          <i class="ti-package"></i>
          <h6>Free Shipping Method</h6>
          <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
        </div>
      </div>
      <div class="col-xl-3 col-lg-3 col-md-6">
        <div class="single-method mb-40">
          <i class="ti-unlock"></i>
          <h6>Secure Payment System</h6>
          <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
        </div>
      </div>
      <div class="col-xl-3 col-lg-3 col-md-6">
        <div class="single-method mb-40">
          <i class="ti-reload"></i>
          <h6>Secure Payment System</h6>
          <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Shop Method End-->
<!-- subscribe part here -->
<section class="subscribe_part section_padding">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="subscribe_part_content">
          <h2>Get promotions & updates!</h2>
          <p>Seamlessly empower fully researched growth strategies and interoperable internal or “organic” sources credibly innovate granular internal .</p>
          <div class="subscribe_form">
            <input type="email" placeholder="Enter your mail">
            <a href="#" class="btn_1">Subscribe</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script>
  function displaySelectedCategory() {
    var selectBox = document.getElementById("categorySelect");
    var selectedValue = selectBox.options[selectBox.selectedIndex].text;
    document.getElementById("selectedCategory").innerHTML = "Selected category: " + selectedValue;
  }
</script>