ClothesWeb/Models/Charts.cs
namespace ClothesWeb.Models
{
  public class Charts
  {
  }

  public class ChartData
  {
    public int Month { get; set; }  // Month number (1-12)
    public int Year { get; set; }
    public double TotalSales { get; set; }  // Total sales for the month
  }

  public class ChartViewModel
  {
    public List<ChartData> ChartData { get; set; }
  }

}

ClothesWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ClothesWeb.Areas.Identity.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ReturnUrl { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string ErrorMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl ??= Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

ClothesWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading;
using System.Threading.Tasks;
using ClothesWeb.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;

namespace ClothesWeb.Areas.Identity.Pages.Account
{
  public class RegisterModel : PageModel
  {
    private readonly SignInManager<IdentityUser> _signInManager;
    private readonly UserManager<IdentityUser> _userManager;
    private readonly IUserStore<IdentityUser> _userStore;
    private readonly IUserEmailStore<IdentityUser> _emailStore;
    private readonly ILogger<RegisterModel> _logger;
    private readonly IEmailSender _emailSender;
    private readonly RoleManager<IdentityRole> _roleManager;

    public RegisterModel(
            UserManager<IdentityUser> userManager,
            IUserStore<IdentityUser> userStore,
            SignInManager<IdentityUser> signInManager,
            ILogger<RegisterModel> logger,
            IEmailSender emailSender,
            RoleManager<IdentityRole> roleManager)
    {
      _userManager = userManager;
      _userStore = userStore;
      _emailStore = GetEmailStore();
      _signInManager = signInManager;
      _logger = logger;
      _emailSender = emailSender;
      _roleManager = roleManager;
    }

    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [BindProperty]
    public InputModel Input { get; set; }

    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public string ReturnUrl { get; set; }

    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public IList<AuthenticationScheme> ExternalLogins { get; set; }

    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public class InputModel
    {
      /// <summary>
      ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
      ///     directly from your code. This API may change or be removed in future releases.
      /// </summary>
      [Required]
      [EmailAddress]
      [Display(Name = "Email")]
      public string Email { get; set; }

      /// <summary>
      ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
      ///     directly from your code. This API may change or be removed in future releases.
      /// </summary>
      [Required]
      [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
      [DataType(DataType.Password)]
      [Display(Name = "Password")]
      public string Password { get; set; }

      /// <summary>
      ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
      ///     directly from your code. This API may change or be removed in future releases.
      /// </summary>
      [DataType(DataType.Password)]
      [Display(Name = "Confirm password")]
      [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
      public string ConfirmPassword { get; set; }

      [Required]
      public string Name { get; set; }
      public string UserName { get; set; }
      public string? Address { get; set; }
      public string? Role { get; set; }
      public string? PhoneNumber { get; set; }
      [ValidateNever]
      public IEnumerable<SelectListItem> RoleList { get; set; }
    }

    public async Task OnGetAsync(string returnUrl = null)
    {
      // Method này sẽ được gọi khi vào trang đăng ký
      if (!_roleManager.RoleExistsAsync("Admin").GetAwaiter().GetResult())
      {
        _roleManager.CreateAsync(new IdentityRole("Admin")).GetAwaiter().GetResult();
        _roleManager.CreateAsync(new IdentityRole("User")).GetAwaiter().GetResult();
      }

      ReturnUrl = returnUrl;
      ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

      // Doi tuong Input de chon role trong khi dang ky!!!!
      Input = new InputModel()
      {
        RoleList = _roleManager.Roles.Select(x => new SelectListItem
        {
          Text = x.Name,
          Value = x.Name
        }),
      };
    }

    public async Task<IActionResult> OnPostAsync(string returnUrl = null)
    {
      returnUrl ??= Url.Content("~/");
      ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
      if (ModelState.IsValid)
      {
        var user = CreateUser();

        // Input la thong tin nhap vao trong form
        user.Name = Input.Name;
        user.Address = Input.Address;
        user.PhoneNumber = Input.PhoneNumber;

        await _userStore.SetUserNameAsync(user, Input.Email, CancellationToken.None);
        await _emailStore.SetEmailAsync(user, Input.Email, CancellationToken.None);

        var result = await _userManager.CreateAsync(user, Input.Password);

        if (result.Succeeded)
        {
          if (Input.Role == null)
          {
            await _userManager.AddToRoleAsync(user, "User");
          }
          else
          {
            await _userManager.AddToRoleAsync(user, Input.Role);
          }

          _logger.LogInformation("User created a new account with password.");

          var userId = await _userManager.GetUserIdAsync(user);
          var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
          code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
          var callbackUrl = Url.Page(
              "/Account/ConfirmEmail",
              pageHandler: null,
              values: new { area = "Identity", userId = userId, code = code, returnUrl = returnUrl },
              protocol: Request.Scheme);

          await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
              $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

          if (_userManager.Options.SignIn.RequireConfirmedAccount)
          {
            return RedirectToPage("RegisterConfirmation", new { email = Input.Email, returnUrl = returnUrl });
          }
          else
          {
            await _signInManager.SignInAsync(user, isPersistent: false);
            return LocalRedirect(returnUrl);
          }
        }
        foreach (var error in result.Errors)
        {
          ModelState.AddModelError(string.Empty, error.Description);
        }
      }

      // If we got this far, something failed, redisplay form
      return Page();
    }

    private ApplicationUser CreateUser()
    {
      try
      {
        return Activator.CreateInstance<ApplicationUser>();
      }
      catch
      {
        throw new InvalidOperationException($"Can't create an instance of '{nameof(ApplicationUser)}'. " +
            $"Ensure that '{nameof(IdentityUser)}' is not an abstract class and has a parameterless constructor, or alternatively " +
            $"override the register page in /Areas/Identity/Pages/Account/Register.cshtml");
      }
    }

    private IUserEmailStore<IdentityUser> GetEmailStore()
    {
      if (!_userManager.SupportsUserEmail)
      {
        throw new NotSupportedException("The default UI requires a user store with email support.");
      }
      return (IUserEmailStore<IdentityUser>)_userStore;
    }
  }
}

ClothesWeb/ViewComponents/AdminPhanloaiViewComponent.cs
using ClothesWeb.Data;
using ClothesWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace ClothesWeb.ViewComponents
{
  public class AdminPhanloaiViewComponent : ViewComponent
  {
    private readonly ApplicationDbContext _db;

    public AdminPhanloaiViewComponent(ApplicationDbContext db)
    {
      _db = db;
    }

    public IViewComponentResult Invoke()
    {
      //Get products category
      IEnumerable<Category> cat = _db.Categories.ToList();
      return View(cat);
    }
  }
}

ClothesWeb/Areas/Owner/Views/Admin/AdminProducts.cshtml
@model IEnumerable<Product>

@{

  Pager pager = new Pager();
  int pageNo = 0;
  if (ViewBag.Pager != null)
  {
    pager = ViewBag.Pager;
    pageNo = pager.CurentPage;
  }
}


<div class="container-fluid">
  <div class="row">
    <h1 class="m-4 text-center">Danh sách sản phẩm</h1>

    <form class="input-group rounded" action="TimKiemSanPham" method="get">
      <input type="search" name="name" class="form-control rounded" placeholder="Search Products" aria-label="Search" aria-describedby="search-addon" />
      <button class="input-group-text border-0 text-dark" id="search-addon" value="Search" asp-controller="Admin" asp-action="TimKiemSanPham">
        <i class="fas fa-search"></i>
      </button>
    </form>

    @*<div class="single_sedebar">
        <div class="select_option">
          <div class="select_option_list">Category <i class="right fas fa-caret-down"></i> </div>
          @await Component.InvokeAsync("AdminPhanloai")
        </div>
      </div>*@

    <hr style="margin: 4rem 0;" />

    @if (Model != null)
    {
      @foreach (var item in Model)
      {
        <div class="col-sm-6 col-xl-3" id="box">
          <div class="card overflow-hidden rounded-2 border shadow">
            <div class="position-relative w-60">
              <a href="javascript:void(0)"><img style="width: 262px; height: 262px;" src="@item.ImageUrl" class="card-img-top rounded-0" alt="..."></a>
              <a href="javascript:void(0)" class="bg-primary rounded-circle p-2 text-white d-inline-flex position-absolute bottom-0 end-0 mb-n3 me-3"
                 data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Add To Cart"><i class="ti ti-basket fs-4"></i></a>
            </div>
            <div class="card-body pt-3 p-4">
              <h6 class="fw-semibold fs-4 truncate-text">@item.Name</h6>
              <div class="d-flex flex-column align-items-center justify-content-between">
                <h6 class="fw-semibold fs-4 mb-0">@String.Format("{0:0,0}", @item.Price)đ<span class="ms-2 fw-normal text-muted fs-3"><del>999,000đ</del></span></h6>

                <ul class="list-unstyled d-flex align-items-center mb-0">
                  <li><a class="me-1" href="javascript:void(0)"><i class="ti ti-star text-warning"></i></a></li>
                  <li><a class="me-1" href="javascript:void(0)"><i class="ti ti-star text-warning"></i></a></li>
                  <li><a class="me-1" href="javascript:void(0)"><i class="ti ti-star text-warning"></i></a></li>
                  <li><a class="me-1" href="javascript:void(0)"><i class="ti ti-star text-warning"></i></a></li>
                  <li><a class="" href="javascript:void(0)"><i class="ti ti-star text-warning"></i></a></li>
                </ul>
              </div>
            </div>
            <div class="d-flex flex-column">
              <a class="btn btn-warning rounded-0" asp-action="Upsert" asp-route-id="@item.IdProduct">Cập nhật</a>
              <a class="btn btn-secondary rounded-0" asp-controller="Admin" asp-action="Product_Details" asp-route-productId="@item.IdProduct">Chi tiết</a>
              <a class="btn btn-danger rounded-0" onclick="Xoa(@item.IdProduct, $(this))">Xóa</a>
            </div>
          </div>
        </div>
      }
    }
    <div class="container">
      @if (pager.TotalPages > 0)
      {
        <ul class="pagination justify-content-center">
          @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
          {
            <li class="page-item @(pge == pager.CurentPage ? "active" : "")">
              <a class="page-link" asp-controller="Admin"
                 asp-action="AdminProducts"
                 asp-route-page="@pge">@pge</a>
              </li>
            }
        </ul>
      }
    </div>
    <span>
      <a asp-controller="Admin" asp-action="Upsert" class="btn btn-primary">Tạo mới</a>
    </span>
  </div>
</div>

ClothesWeb/Areas/Owner/Views/Admin/Analytics.cshtml
<div class="container-fluid mt-5">
  <div class="d-flex flex-wrap justify-content-evenly align-items-center fs-5">
    <div style="width: 300px; height: auto; padding: 20px; background-color: #f5f5f5;">
      <div class="card-body">
        <h5 class="card-title">Tổng sản phẩm</h5>
        <a asp-area="Owner" asp-controller="Admin" asp-action="AdminProducts" id="increaseBtn" class="btn btn-primary card-text">@ViewBag.TotalProduct</a>
      </div>
    </div>
    <div style="width: 300px; height: auto; padding: 20px; background-color: #f5f5f5;">
      <div class="card-body align-content-center">
        <h5 class="card-title">Tổng loại sản phẩm</h5>
        @*Owner/Admin/ViewLoaiSanPham*@
        <a asp-area="Owner" asp-controller="Admin" asp-action="ViewLoaiSanPham" id="increaseBtn" class="btn btn-primary card-text">@ViewBag.TotalCategories</a>
      </div>
    </div>
    <div style="width: 300px; height: auto; padding: 20px; background-color: #f5f5f5;">
      <div class="card-body align-content-center">
        <h5 class="card-title">Tổng đơn hàng</h5>
        @*Owner/DonHang*@
        <a asp-area="Owner" asp-controller="DonHang" asp-action="Index" id="increaseBtn" class="btn btn-primary card-text">@ViewBag.TotalSL</a>
      </div>
    </div>

    <div class="p-4 bg-light mt-5">
      <h4>Biểu đồ doanh thu</h4>
      <div>
        <canvas id="myLineChart" height="400" width="1000"></canvas>
      </div>
    </div>
  </div>
</div>
@section Scripts {
  <partial name="_ValidationScriptsPartial" />
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js" integrity="sha512-L0Shl7nXXzIlBSUUPpxrokqq4ojqgZFQczTYlGjzONGTDAcLremjwaWv5A+EDLnxhQzY5xUZPWLOLqYRkY0Cbw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>
    var fakeData = [
      { month: 1, totalRevenue: 10000, profit: 5000 },
      { month: 2, totalRevenue: 12000, profit: 6000 },
      { month: 3, totalRevenue: 15000, profit: 7000 },
      { month: 4, totalRevenue: 18000, profit: 8000 },
      { month: 5, totalRevenue: 20000, profit: 8500 },
      { month: 6, totalRevenue: 22000, profit: 9000 },
      { month: 7, totalRevenue: 25000, profit: 9500 },
      { month: 8, totalRevenue: 27000, profit: 10000 },
      { month: 9, totalRevenue: 28000, profit: 10500 },
      { month: 10, totalRevenue: 30000, profit: 11000 },
      { month: 11, totalRevenue: 32000, profit: 11500 },
      { month: 12, totalRevenue: 35000, profit: 12000 }
    ];
    //$(document).ready(function () {
    //  // Thay thế fakeData bằng dữ liệu thực tế từ AJAX
    //  drawChart(fakeData);
    //});

    $(document).ready(function () {
      $.ajax({
        url: '/Owner/Admin/MonthlySales',
        type: 'GET',
        success: function (data) {
          drawChart(data);
        }
      });
    });

    function drawChart(data) {
      //const months = data.map(item => item.month);
      //const revenue = data.map(item => item.totalRevenue);
      //const profit = data.map(item => item.profit);

      var months = [];
      var revenues = [];
      var profits = [];

      for (var i = 0; i < data.length; i++) {
        months.push(data[i].month + '/' + data[i].year); // Tạo chuỗi thể hiện tháng/năm
        revenues.push(data[i].totalRevenue);
        profits.push(data[i].totalProfit);
      }

      var ctx = document.getElementById('myLineChart').getContext('2d');
      var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: months,
          datasets: [
            {
              label: 'Doanh thu',
              data: revenues,
              backgroundColor: '#1875f0',
              borderColor: '#000',
              borderWidth: 1
            },
            {
              label: 'Lợi nhuận',
              data: profits,
              backgroundColor: '#50d166',
              borderColor: '#000',
              borderWidth: 1
            }
          ]
        },
        options: {
          scales: {
            y: {
              beginAtZero: true
            }
          }
        }
      });
    }

  </script>
}

ClothesWeb/Areas/Owner/Views/Admin/ListUser.cshtml
@model IEnumerable<ApplicationUser>

@{
  Layout = "_LayoutAdmin";
  Pager pager = new Pager();
  int pageNo = 0;
  if (ViewBag.Pager != null)
  {
    pager = ViewBag.Pager;
    pageNo = pager.CurentPage;
  }
}

<div class="col-lg-10">
  <div class="card rounded shadow border-0">
    <div class="card-body p-5 bg-white rounded">
      <div class="table-responsive">
        <h2>Danh sách người dùng</h2>
        @if (Model.Any())
        {
          <table class="table table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>User Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Address</th>
                <th>Chức năng</th>
              </tr>
            </thead>
            <tbody>
              @foreach (var item in Model)
              {
                <tr id="box">
                  <td></td>
                  <td>@item.Id</td>
                  <td>@item.Name</td>
                  <td>@item.Email</td>
                  <td>@item.Address</td>
                  <td class="d-flex flex-column">
                    <a asp-controller="Admin" asp-action="EditUser" asp-route-id="@item.Id" class="btn btn-success mb-2">Cập nhật</a>
                    <a asp-controller="Admin" asp-action="DeleteUser" asp-route-id="@item.Id" class="btn btn-danger mb-2" onclick="Xoa(@item.Id, $(this))">Xóa</a>
                  </td>
                </tr>
              }
            </tbody>
          </table>
        }
        else
        {
          <div class="card">
            <div class="card-header">
              Không có người dùng
            </div>
            <div class="card-body">
              <h5 class="cart-title">
                Đăng ký mới
              </h5>
              <a class="btn btn-primary" style="width: auto;" asp-controller="Admin" asp-action="ListUsers">
                Thêm mới người dùng
              </a>
            </div>
          </div>
        }
        <div class="container">
          @if (pager.TotalPages > 0)
          {
            <ul class="pagination justify-content-center">
              @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
              {
                <li class="page-item @(pge == pager.CurentPage ? "active" : "")">
                  <a class="page-link" asp-controller="Admin"
                     asp-action="ListUser"
                     asp-route-page="@pge">@pge</a>
                  </li>
                }
            </ul>
          }
        </div>
      </div>
    </div>
  </div>
</div>

ClothesWeb/Areas/Owner/Views/Admin/Register.cshtml
@{
    Layout = "";
}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Modernize Free</title>
    <link rel="shortcut icon" type="image/png" href="~/assets_admin/images/logos/favicon.png" />
    <link rel="stylesheet" href="~/assets_admin/css/styles.min.css" />
</head>

<body>
    <!--  Body Wrapper -->
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed">
        <div class="position-relative overflow-hidden radial-gradient min-vh-100 d-flex align-items-center justify-content-center">
            <div class="d-flex align-items-center justify-content-center w-100">
                <div class="row justify-content-center w-100">
                    <div class="col-md-8 col-lg-6 col-xxl-3">
                        <div class="card mb-0">
                            <div class="card-body">
                                <a href="#" class="text-nowrap logo-img d-block py-3 w-100 d-flex align-items-center justify-content-center">
                                    <img src="~/assets_admin/images/logos/favicon.png" alt="" />
                                    <div class="text-black" style="font-size: 1.5rem; margin-left: 1rem; font-weight: 700; color: rgba(93, 135, 255, 0.85) !important;">August</div>
                                </a>
                                <p class="text-center">Your Social Campaigns</p>
                                <form>
                                    <div class="mb-3">
                                        <label for="exampleInputtext1" class="form-label">Name</label>
                                        <input type="text" class="form-control" id="exampleInputtext1" aria-describedby="textHelp">
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleInputEmail1" class="form-label">Email Address</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                                    </div>
                                    <div class="mb-4">
                                        <label for="exampleInputPassword1" class="form-label">Password</label>
                                        <input type="password" class="form-control" id="exampleInputPassword1">
                                    </div>
                                    <a asp-controller="Admin" asp-action="Dashboard" class="btn btn-primary w-100 py-8 fs-4 mb-4 rounded-2">Sign Up</a>
                                    <div class="d-flex align-items-center justify-content-center">
                                        <p class="fs-4 mb-0 fw-bold">Already have an Account?</p>
                                        <a class="text-primary fw-bold ms-2" asp-controller="Admin" asp-action="Login">Sign In</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/assets_admin/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/assets_admin/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>