ClothesWeb/Models/DonHang.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClothesWeb.Models
{
  public class DonHang
  {
    [Key]
    public int Id { get; set; }

    public int OrderDetailId { get; set; }
    [ForeignKey("OrderDetailId")]
    [ValidateNever]
    public ChiTietHoaDon ChiTietHoaDon { get; set; }

    public int ProductId { get; set; }
    [ForeignKey("ProductId")]
    [ValidateNever]
    public Product Product { get; set; }

    public int HoaDonId { get; set; }
    [ForeignKey("HoaDonId")]
    [ValidateNever]
    public HoaDon HoaDon { get; set; }

    public string ImgUrl { get; set; }
    public string NameProduct { get; set; }
    public double PriceOfProduct { get; set; }
    public double Total { get; set; }
    public int Quantity { get; set; }
    public DateTime? OrderDate { get; set; }
    public string? OrderStatus { get; set; }
    public bool IsCheckout { get; set; }
  }
}

ClothesWeb/Areas/Owner/Controllers/DonHangController.cs
using Azure;
using ClothesWeb.Data;
using ClothesWeb.Migrations;
using ClothesWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace ClothesWeb.Areas.Owner.Controllers
{
  [Area("Owner")]
  public class DonHangController : Controller
  {
    private readonly ApplicationDbContext _db;

    public DonHangController(ApplicationDbContext db)
    {
      _db = db;
    }

    public IActionResult Index(int page = 1)
    {
      IEnumerable<HoaDon> hoadons = _db.HoaDons.Include(x => x.User).OrderByDescending(x => x.OrderDate).ToList();
      const int pageSize = 12;
      page = page < 1 ? 1 : page;
      int recsCount = hoadons.Count();
      var pager = new Pager(recsCount, page, pageSize);
      int recSkip = (page - 1) * pageSize;
      var data = hoadons.Skip(recSkip).Take(pager.PageSize).ToList();
      this.ViewBag.Pager = pager;
      return View(data);
    }

    public IActionResult DonHangDetail(int donHangId)
    {
      var detailsOrder = _db.ChiTietHoaDons.
        Include(od => od.Product)
        .Where(od => od.HoaDonId == donHangId)
        .ToList();
      return View(_db.HoaDons.OrderByDescending(p => p.Id).ToList());
    }

    public IActionResult XacNhan(int donHangId)
    {
      var hoadon = _db.HoaDons.FirstOrDefault(x => x.Id == donHangId);
      if (hoadon != null)
      {
        hoadon.OrderStatus = "Đã xác nhận";
        _db.SaveChanges();
      }
      return View(hoadon);
    }

    public IActionResult DonhangDetailsAdmin(int id)
    {
      var chiTietHoaDonList = _db.ChiTietHoaDons
                                  .Include("HoaDon")
                                  .Where(chiTiet => chiTiet.HoaDonId == id)
                                  .ToList();

      var hoadon = _db.HoaDons.Where(x => x.Id == id).FirstOrDefault();
      if (hoadon != null)
      {
        ViewBag.Total = hoadon.TotalPrice;
        ViewBag.Name = hoadon.Name;
        ViewBag.Address = hoadon.Address;
        ViewBag.PhoneNumber = hoadon.PhoneNumber;
        ViewBag.GhiChu = hoadon.GhiChu;
        ViewBag.OrderStatus = hoadon.OrderStatus;
        if (chiTietHoaDonList.Any())
        {
          return View(chiTietHoaDonList);
        }
      }

      return NotFound();
    }

    public IActionResult DonhangDeleteAdmin(int id)
    {
      var donhangDelete = _db.HoaDons.FirstOrDefault(c => c.Id == id);
      if (donhangDelete == null)
      {
        return NotFound();
      }
      _db.HoaDons.Remove(donhangDelete);
      _db.SaveChanges();

      return RedirectToAction("Index");
    }
  }
}

ClothesWeb/Areas/Owner/Views/DonHang/DonHangDetail.cshtml
@model List<ChiTietHoaDon>

@{
  Layout = "";
  Pager pager = new Pager();
  int pageNo = 0;
  if (ViewBag.Pager != null)
  {
    pager = ViewBag.Pager;
    pageNo = pager.CurentPage;
  }
}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Modernize Free</title>
  <link rel="shortcut icon" type="image/png" href="~/assets_admin/images/logos/favicon.png" />
  <link rel="stylesheet" href="~/assets_admin/css/styles.min.css" />
  <style>
    body {
      min-height: 100vh;
      background-color: #FFE53B;
      background-image: linear-gradient(147deg, #FFE53B 0%, #FF2525 100%);
    }

    .container-card {
      width: 100%;
      margin: 0 auto;
      text-align: center;
    }
  </style>
</head>

<body>
  @*Body Wrapper*@
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
       data-sidebar-position="fixed" data-header-position="fixed">
    @*Sidebar Start*@
    <aside class="left-sidebar">
      @*Sidebar scroll*@
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-center">
          <a asp-controller="Admin" asp-action="Dashboard" class="text-nowrap logo-img d-flex align-items-center justify-content-between">
            <img src="~/assets_admin/images/logos/favicon.png" alt="" />
            <div class="text-black" style="font-size: 1.5rem; margin-left: 1rem; font-weight: 700; color: rgba(93, 135, 255, 0.85) !important;">Admin</div>
          </a>
          <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
            <i class="ti ti-x fs-8"></i>
          </div>
        </div>
        @*Sidebar navigation*@
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
          <ul id="sidebarnav">
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Home</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" asp-controller="Admin" asp-action="Dashboard" aria-expanded="false">
                <span>
                  <i class="ti ti-layout-dashboard"></i>
                </span>
                <span class="hide-menu">Dashboard</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">SẢN PHẨM</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" asp-controller="Admin" asp-action="AdminProducts" aria-expanded="false">
                <span>
                  <i class="ti ti-article"></i>
                </span>
                <span class="hide-menu">Trang sản phẩm</span>
              </a>
            </li>

            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">TÀI KHOẢN</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" asp-controller="Admin" asp-action="UserAccount" aria-expanded="false">
                <span>
                  <i class="ti ti-user-circle"></i>
                </span>
                <span class="hide-menu">Quản lý tài khoản người dùng</span>
              </a>
            </li>

            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Đơn hàng</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" asp-controller="DonHang" asp-action="Index" aria-expanded="false">
                <span>
                  <i class="ti ti-shopping-cart"></i>
                </span>
                <span class="hide-menu">Quản lý đơn hàng</span>
              </a>
            </li>

            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Loại sản phẩm</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" asp-controller="DonHang" asp-action="LoaiHang" aria-expanded="false">
                <span>
                  <i class="ti ti-clothes-rack"></i>
                </span>
                <span class="hide-menu">Quản lý loại hàng</span>
              </a>
            </li>
          </ul>
        </nav>
        @*End Sidebar navigation*@
      </div>
      @*End Sidebar scroll*@
    </aside>
    @*Sidebar End
      Main wrapper*@
    <div class="body-wrapper">
      <div class="container mt-5">
        <h2 class="mb-4">Chi tiết đơn hàng</h2>

        <div class="card">
          <div class="card-header">
            Thông tin đơn hàng
          </div>
          <div class="card-body">
            <table class="table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>IdUser</th>
                  <th>Hóa đơn Id</th>
                  <th>Id Sản phẩm</th>
                  <th>Tên khách hàng</th>
                  <th>Số lượng</th>
                  <th>Ngày dặt hàng</th>
                  <th>Trạng thái đơn hàng</th>
                </tr>
              </thead>
              <tbody>
                @foreach (var item in @Model)
                {
                  <tr>
                    <td></td>
                    <td>@item.HoaDon.ApplicationUserId</td>
                    <td>@item.HoaDonId</td>
                    <td>@item.ProductId</td>
                    <td>@item.HoaDon.Name</td>
                    <td>@item.Quantity</td>
                    <td>@item.HoaDon.OrderDate</td>
                    <td>@item.HoaDon.OrderStatus</td>
                  </tr>
                }
              </tbody>
            </table>

            <!-- Tổng tiền -->
            <div class="mt-3">
              @*<h5>Tổng tiền: @Model.TotalAmount</h5>*@
            </div>
          </div>
        </div>
      </div>
    </div>



    <script src="~/assets_admin/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/assets_admin/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets_admin/js/sidebarmenu.js"></script>
    <script src="~/assets_admin/js/app.min.js"></script>
    <script src="~/assets_admin/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="~/assets_admin/libs/simplebar/dist/simplebar.js"></script>
    <script src="~/assets_admin/js/dashboard.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</body>

</html>

ClothesWeb/Areas/Owner/Views/DonHang/DonhangDetailsAdmin.cshtml
@model IEnumerable<ChiTietHoaDon>

@{
  Layout = "_LayoutAdmin";
  Pager pager = new Pager();
  int pageNo = 0;
  if (ViewBag.Pager != null)
  {
    pager = ViewBag.Pager;
    pageNo = pager.CurentPage;
  }
}

<div class="container container-box">
  <div class="w-100 container-card">
    <div class="col-lg-10 mt-5">
      <div class="card rounded shadow border-0">
        <div class="card-body p-5 bg-white rounded">
          <div class="table-responsive">
            @if (Model != null && Model.Any())
            {
              <div class="container">
                <div class="p-4 bg-light-info">
                  <h4 class="text-left">Thông tin khách hàng</h4>
                  <div class="text-left fs-3">
                    <div style="padding: 10px 0 4px 10px; background-color: #f5f5f5; " class="d-flex align-items-center justify-content-start">
                      <div class="me-2">Tên khách hàng: </div>
                      <div>@ViewBag.Name</div>
                    </div>
                    <hr />
                    <div style="padding: 10px 0 4px 10px; background-color: #f5f5f5;" class="d-flex align-items-center justify-content-start">
                      <div>Địa chỉ: </div>
                      <div class="form-inline">@ViewBag.Address</div>
                    </div>
                    <hr />
                    <div style="padding: 10px 0 4px 10px; background-color: #f5f5f5; " class="d-flex align-items-center justify-content-start">
                      <div>Số điện thoại: </div>
                      <div>@ViewBag.PhoneNumber</div>
                    </div>
                    <hr />
                    <div style="padding: 10px 0 4px 10px; background-color: #f5f5f5; " class="d-flex align-items-center justify-content-start">
                      <div>Ghi chú: </div>
                      <div>@ViewBag.GhiChu</div>
                    </div>
                    <hr />
                    <div style="padding: 10px 0 4px 10px; background-color: #f5f5f5; " class="d-flex align-items-center justify-content-start">
                      <div>Tình trạng đơn hàng: </div>
                      <div>@ViewBag.OrderStatus</div>
                    </div>
                  </div>
                </div>
                <hr />
                <h2 class="text-center m-4">Chi tiết đơn hàng</h2>
                <hr />
                <table class="table table-bordered" style="font-size: 16px;">
                  <thead class="text-center">
                    <tr>
                      <th></th>
                      <th>Tên sản phẩm</th>
                      <th>Số lượng</th>
                      <th>Giá tiền</th>
                    </tr>
                  </thead>
                  <tbody class="text-center">
                    @foreach (var item in Model)
                    {
                      <tr>
                        <td><img style="width: 80px; height: 80px;" src="@item.ImgURL" alt="Product Image"></td>
                        <td class="text-start">@item.ProductName</td>
                        <td>@item.Quantity</td>
                        <td>@String.Format("{0:0,0}", item.ProductPrice)</td>
                      </tr>
                    }
                  </tbody>
                </table>
                <div class="container">
                  <hr />
                  <div class="form-control m-2">
                    <div style="color: red; font-size: 20px; text-align: end;">
                      <label class="form-label text-uppercase" style="font-size: 14px; color: #000;">Phí giao hàng:</label>
                      <span style="font-weight: 700;">@String.Format("{0:0,0}", 32000)</span>
                    </div>
                    <hr />
                    <div style="color: red; font-size: 20px; text-align: end;">
                      <label class="form-label text-uppercase" style="font-size: 14px; color: #000;">Thành tiền:</label>
                      <span style="font-weight: 700;">@String.Format("{0:0,0}", @ViewBag.Total)</span>
                    </div>
                  </div>
                  <span><a asp-controller="DonHang" asp-action="Index" class="btn btn-outline-primary">Quay về</a></span>
                </div>
              </div>
            }
            else
            {
              <h3>Không có sản phẩm.</h3>
            }
            @*<div class="container">
                @if (pager.TotalPages > 0)
                {
                  <ul class="pagination justify-content-center">
                    @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                    {
                      <li class="page-item @(pge == pager.CurentPage ? "active" : "")">
                        <a class="page-link" asp-controller="DonHang"
                           asp-action="Index"
                           asp-route-page="@pge">@pge</a>
                        </li>
                      }
                  </ul>
                }
              </div>*@
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

ClothesWeb/Areas/Owner/Views/DonHang/Index.cshtml
@model IEnumerable<HoaDon>

@{
  Pager pager = new Pager();
  int pageNo = 0;
  if (ViewBag.Pager != null)
  {
    pager = ViewBag.Pager;
    pageNo = pager.CurentPage;
  }
}

<div class="container container-box">
  <div class="py-5 w-100 container-card">
    <div class="col-lg-10 mt-5">
      <div class="card rounded shadow border-0">
        <div class="card-body p-5 bg-white rounded">
          <div class="table-responsive">
            <h2>Danh sách đơn hàng</h2>
            @if (Model.Any())
            {
              <table class="table">
                <thead class="text-center align-middle font-weight-bold">
                  <tr>
                    <td>Id</td>
                    <td>Tên khách hàng</td>
                    <td>Số điện thoại</td>
                    <td>Địa chỉ</td>
                    <td>Trạng thái đơn hàng</td>
                    <td>Ngày đặt hàng</td>
                    <td>Tổng tiền</td>
                    <td>Chức năng</td>
                  </tr>
                </thead>
                <tbody>
                  @foreach (var item in @Model)
                  {
                    <tr>
                      <td>@item.Id</td>
                      <td class="text-start">@item.Name</td>
                      <td>@item.PhoneNumber</td>
                      <td class="text-start">@item.Address</td>
                      <td>@item.OrderStatus</td>
                      <td>@item.OrderDate</td>
                      <td>@String.Format("{0:0,0}", item.TotalPrice)</td>
                      @if (item.OrderStatus != "Đã xác nhận")
                      {
                        <td class="d-flex flex-column">
                          <a asp-controller="DonHang" asp-action="XacNhan" asp-route-donHangId="@item.Id" class="btn btn-warning text-white mb-2">Xác nhận</a>
                          <a asp-controller="DonHang" asp-action="DonhangDetailsAdmin" asp-route-id="@item.Id" class="btn btn-primary text-white mb-2">Chi tiết</a>
                          <a class="btn btn-danger text-white mb-2" onclick="Xoa('@item.Id', $(this))">Xóa</a>
                        </td>
                      }
                      else
                      {
                        <td class="d-flex flex-column">
                          <p class="btn btn-success text-white mb-2">Đã duyệt</p>
                          <a asp-controller="DonHang" asp-action="DonhangDetailsAdmin" asp-route-id="@item.Id" class="btn btn-primary text-white mb-2">Chi tiết</a>
                          <a class="btn btn-danger text-white mb-2" onclick="Xoa('@item.Id', $(this))">Xóa</a>

                        </td>
                      }
                    </tr>
                  }
                </tbody>
              </table>
            }
            else
            {
              <div class="card">
                <div class="card-header">
                  Không có đơn hàng
                </div>
              </div>
            }
            <div class="container">
              @if (pager.TotalPages > 0)
              {
                <ul class="pagination justify-content-center">
                  @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                  {
                    <li class="page-item @(pge == pager.CurentPage ? "active" : "")">
                      <a class="page-link" asp-controller="DonHang"
                         asp-action="Index"
                         asp-route-page="@pge">@pge</a>
                      </li>
                    }
                </ul>
              }
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>