ClothesWeb/ViewComponents/CartViewComponent.cs
using ClothesWeb.Data;
using ClothesWeb.Migrations;
using ClothesWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace ClothesWeb.ViewComponents
{
  [Area("Customer")]
  [Authorize]
  public class CartViewComponent : ViewComponent
  {
    private readonly ApplicationDbContext _db;

    public CartViewComponent(ApplicationDbContext db)
    {
      _db = db;
    }

    public IViewComponentResult Invoke()
    {
      // is Login
      if (User.Identity.IsAuthenticated)
      {
        var identity = (ClaimsIdentity)User.Identity;
        var claim = identity.FindFirst(ClaimTypes.NameIdentifier);

        CartViewModel cart = new CartViewModel()
        {
          listCart = _db.Carts
          .Include("Product")
          .Where(x => x.ApplicationUserId == claim.Value).ToList()
        };
        return View(cart);
      }
      else { return View(new CartViewModel()); }
    }
  }
}

ClothesWeb/ViewComponents/CategoryViewComponent.cs
using ClothesWeb.Data;
using ClothesWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace ClothesWeb.ViewComponents
{
  public class CategoryViewComponent : ViewComponent
  {
    private readonly ApplicationDbContext _db;

    public CategoryViewComponent(ApplicationDbContext db)
    {
      _db = db;
    }

    public IViewComponentResult Invoke()
    {
      //Get products category
      IEnumerable<Category> cat = _db.Categories.ToList();
      return View(cat);
    }
  }
}

ClothesWeb/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="zxx">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Clothes Website </title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="manifest" href="site.webmanifest">
  <link rel="shortcut icon" type="image/x-icon" href="~/assets/img/favicon.ico">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400&display=swap" rel="stylesheet">

  <!-- CSS here -->
  <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
  <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
  <link rel="stylesheet" href="~/assets/css/flaticon.css">
  <link rel="stylesheet" href="~/assets/css/slicknav.css">
  <link rel="stylesheet" href="~/assets/css/animate.min.css">
  <link rel="stylesheet" href="~/assets/css/magnific-popup.css">
  <link rel="stylesheet" href="~/assets/css/fontawesome-all.min.css">
  <link rel="stylesheet" href="~/assets/css/themify-icons.css">
  <link rel="stylesheet" href="~/assets/css/slick.css">
  <link rel="stylesheet" href="~/assets/css/nice-select.css">
  <link rel="stylesheet" href="~/assets/css/style.css">
  <link rel="stylesheet" href="~/assets/css/cart.css">
</head>

<body>

  <!-- Preloader Start -->
  <div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
      <div class="preloader-inner position-relative">
        <div class="preloader-circle"></div>
        <div class="preloader-img pere-text">
          <img src="~/assets/img/logo/logo.png" alt="">
        </div>
      </div>
    </div>
  </div>
  <!-- Preloader Start -->

  <header>
    <!-- Header Start -->
    <div class="header-area">
      <div class="main-header ">
        <div class="header-top top-bg d-none d-lg-block">
          <div class="container-fluid">
            <div class="col-xl-12">
              <div class="row d-flex justify-content-between align-items-center">
                <div class="header-info-left d-flex">
                  <div class="flag">
                    <img src="~/assets/img/icon/header_icon.png" alt="">
                  </div>
                  <div class="select-this">
                    <form action="#">
                      <div class="select-itms">
                        <select name="select" id="select1">
                          <option value="">USA</option>
                          <option value="">SPN</option>
                          <option value="">CDA</option>
                          <option value="">USD</option>
                        </select>
                      </div>
                    </form>
                  </div>
                  <ul class="contact-now">
                    <li>+777 2345 7886</li>
                  </ul>
                </div>
                <div class="header-info-right">
                  <ul>
                    <li><a asp-controller="Home" asp-action="Login">My Account</a></li>
                    <li><a asp-controller="Home" asp-action="Confirmation">Confirmation</a></li>
                    <li><a asp-controller="Home" asp-action="Category">Shopping</a></li>
                    <li><a asp-controller="Cart" asp-action="Index">Cart</a></li>
                    <li><a asp-controller="Home" asp-action="Checkout">Checkout</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="header-bottom  header-sticky">
          <div class="container-fluid">
            <div class="row align-items-center">
              <!-- Logo -->
              <div class="col-xl-1 col-lg-1 col-md-1 col-sm-3">
                <div class="logo">
                  <a asp-controller="Home" asp-action="Index"><img src="~/assets/img/logo/logo.png" alt=""></a>
                </div>
              </div>
              <div class="col-xl-6 col-lg-8 col-md-7 col-sm-5">
                <!-- Main-menu -->
                <div class="main-menu f-right d-none d-lg-block">
                  <nav>
                    <ul id="navigation">
                      <li>
                        <a asp-controller="Home" asp-action="Index">Home</a>
                      </li>

                      <li>
                        <a asp-controller="Home" asp-action="Catagori" asp-route-loaiId=0>Shop</a>
                        <vc:category></vc:category>
                      </li>

                      <!--<li class="hot">
                        <a asp-controller="Home" asp-action="Catagori">Shop</a>
                        <!--<ul class="submenu">
                          <li><a asp-controller="Home" asp-action="Product_List" asp-route-loaId=0> Product list</a></li>-->
                          <!--@*<li><a asp-controller="Home" asp-action="Product_Details">Product Details</a></li>*@-->
                        <!--</ul>-->
                      <!--</li>-->

                      <li>
                        <a asp-controller="Home" asp-action="Blogvion=" Blog_Details">Blog Details</a>
                      </li>
                      <li><a asp-controller="Home" asp-action="About">About</a></li>
                      <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                  </nav>
                </div>
              </div>
              <div class="col-xl-5 col-lg-3 col-md-3 col-sm-3 fix-card">
                <ul class="header-right f-right d-none d-lg-block d-flex align-items-center justify-content-between">
                  <li class="d-none d-xl-block">
                    @* SEARCH Ở ĐÂY *@
                    <div class="form-box f-right">
                      <form action="TimKiemSanPham" method="get">
                        <input type="text" name="name" placeholder="Search products" class="form-control">
                        <button type="submit" class="search-icon" value="Search" asp-controller="Home" asp-action="TimKiemSanPham">
                          <i class="fas fa-search special-tag"></i>
                        </button>
                      </form>
                    </div>
                  </li>
                  <li class="d-none d-xl-block">
                    <div class="favorit-items">
                      <i class="far fa-heart"></i>
                    </div>
                  </li>

                  <li class="d-none d-xl-block">
                    <div class="shopping-card">
                      <div class="header__cart">
                        <div class="header__cart-wrap">
                          <a asp-controller="Cart" asp-action="Index"><i class="fas fa-shopping-cart"></i></a>
                          <vc:cart></vc:cart>
                        </div>
                      </div>
                    </div>
                  </li>

                  @*<li class="d-none d-lg-block"> <a asp-controller="Home" asp-action="Login" class="btn header-btn">Sign in</a></li>*@

                  @*REGISTER LOGIN*@
                  <li class="d-none d-xl-block nav-item dropdown">
                    <partial name="_LoginPartial" />
                  </li>
                </ul>
              </div>

              <!-- Mobile Menu -->
              <div class="col-12">
                <div class="mobile_menu d-block d-lg-none"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Header End -->
  </header>
  @RenderBody()
  <footer>

    <!-- Footer Start-->
    <div class="footer-area footer-padding">
      <div class="container">
        <div class="row d-flex justify-content-between">
          <div class="col-xl-3 col-lg-3 col-md-5 col-sm-6">
            <div class="single-footer-caption mb-50">
              <div class="single-footer-caption mb-30">
                <!-- logo -->
                <div class="footer-logo">
                  <a asp-controller="Home" asp-action="Index"><img src="~/assets/img/logo/logo2_footer.png" alt=""></a>
                </div>
                <div class="footer-tittle">
                  <div class="footer-pera">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-2 col-lg-3 col-md-3 col-sm-5">
            <div class="single-footer-caption mb-50">
              <div class="footer-tittle">
                <h4>Quick Links</h4>
                <ul>
                  <li><a asp-controller="Home" asp-action="About">About</a></li>
                  <li><a href="#"> Offers & Discounts</a></li>
                  <li><a href="#"> Get Coupon</a></li>
                  <li><a asp-controller="Home" asp-action="Contact">  Contact Us</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-lg-3 col-md-4 col-sm-7">
            <div class="single-footer-caption mb-50">
              <div class="footer-tittle">
                <h4>New Products</h4>
                <ul>
                  <li><a href="#">Woman Cloth</a></li>
                  <li><a href="#">Fashion Accessories</a></li>
                  <li><a href="#"> Man Accessories</a></li>
                  <li><a href="#"> Rubber made Toys</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-lg-3 col-md-5 col-sm-7">
            <div class="single-footer-caption mb-50">
              <div class="footer-tittle">
                <h4>Support</h4>
                <ul>
                  <li><a href="#">Frequently Asked Questions</a></li>
                  <li><a href="#">Terms & Conditions</a></li>
                  <li><a href="#">Privacy Policy</a></li>
                  <li><a href="#">Privacy Policy</a></li>
                  <li><a href="#">Report a Payment Issue</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!-- Footer bottom -->
        <div class="row">
          <div class="col-xl-7 col-lg-7 col-md-7">
            <div class="footer-copy-right">
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;
              <script>document.write(new Date().getFullYear());</script>
              <i class="ti-heart" aria-hidden="true"></i><a href="https://colorlib.com" target="_blank"></a>

              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
            </div>
          </div>
          <div class="col-xl-5 col-lg-5 col-md-5">
            <div class="footer-copy-right f-right">
              <!-- social -->
              <div class="footer-social">
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-behance"></i></a>
                <a href="#"><i class="fas fa-globe"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Footer End-->

  </footer>

  <!-- JS here -->
  <!-- All JS Custom Plugins Link Here here -->
  <script src="~/assets/js/vendor/modernizr-3.5.0.min.js"></script>
  <!-- Jquery, Popper, Bootstrap -->
  <script src="~/assets/js/vendor/jquery-1.12.4.min.js"></script>
  <script src="~/assets/js/popper.min.js"></script>
  <script src="~/assets/js/bootstrap.min.js"></script>
  <!-- Jquery Mobile Menu -->
  <script src="~/assets/js/jquery.slicknav.min.js"></script>

  <!-- Jquery Slick , Owl-Carousel Plugins -->
  <script src="~/assets/js/owl.carousel.min.js"></script>
  <script src="~/assets/js/slick.min.js"></script>

  <!-- One Page, Animated-HeadLin -->
  <script src="~/assets/js/wow.min.js"></script>
  <script src="~/assets/js/animated.headline.js"></script>
  <script src="~/assets/js/jquery.magnific-popup.js"></script>

  <!-- Scrollup, nice-select, sticky -->
  <script src="~/assets/js/jquery.scrollUp.min.js"></script>
  <script src="~/assets/js/jquery.nice-select.min.js"></script>
  <script src="~/assets/js/jquery.sticky.js"></script>

  <!-- contact js -->
  <script src="~/assets/js/contact.js"></script>
  <script src="~/assets/js/jquery.form.js"></script>
  <script src="~/assets/js/jquery.validate.min.js"></script>
  <script src="~/assets/js/mail-script.js"></script>
  <script src="~/assets/js/jquery.ajaxchimp.min.js"></script>

  <!-- Jquery Plugins, main Jquery -->
  <script src="~/assets/js/plugins.js"></script>
  <script src="~/assets/js/main.js"></script>

  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ClothesWeb/Views/Shared/_LayoutAdmin.cshtml
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Dashboard</title>
  <link rel="shortcut icon" type="image/png" href="~/assets_admin/images/logos/favicon.png" />
  <link rel="stylesheet" href="~/assets_admin/css/styles.min.css" />
  <link href="Content/sweetalert/sweet-alert.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400&display=swap" rel="stylesheet">

  <style>
    .truncate-text {
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
      max-width: 200px;
    }

    body {
      min-height: 100vh;
      background-color: #FFE53B;
      background-image: linear-gradient(147deg, #FFE53B 0%, #FF2525 100%);
    }
  </style>
</head>
<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
       data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->
    <aside class="left-sidebar">
      <!-- Sidebar scroll-->
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-center">
          <a asp-controller="Admin" asp-action="Dashboard" class="text-nowrap logo-img d-flex align-items-center justify-content-between">
            <img src="~/assets_admin/images/logos/favicon.png" alt="" />
            <div class="text-black" style="font-size: 1.5rem; margin-left: 1rem; font-weight: 700; color: rgba(93, 135, 255, 0.85) !important;">Admin</div>
          </a>
          <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
            <i class="ti ti-x fs-8"></i>
          </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
          <ul id="sidebarnav">
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Home</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" asp-controller="Admin" asp-action="Dashboard" aria-expanded="false">
                <span>
                  <i class="ti ti-layout-dashboard"></i>
                </span>
                <span class="hide-menu">Dashboard</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" asp-controller="Admin" asp-action="Analytics" aria-expanded="false">
                <span>
                  <i class="ti ti-layout-dashboard"></i>
                </span>
                <span class="hide-menu">Analytics</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">SẢN PHẨM</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" asp-controller="Admin" asp-action="AdminProducts" aria-expanded="false">
                <span>
                  <i class="ti ti-article"></i>
                </span>
                <span class="hide-menu">Trang sản phẩm</span>
              </a>
            </li>
            <!-- SỬA TẠI ĐÂY -->

            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Tài khoản</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" asp-controller="Admin" asp-action="ListUser" aria-expanded="false">
                <span>
                  <i class="ti ti-user-circle"></i>
                </span>
                <span class="hide-menu">Quản lý tài khoản User</span>
              </a>
            </li>

            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Đơn hàng</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" asp-controller="DonHang" asp-action="Index" aria-expanded="false">
                <span>
                  <i class="ti ti-shopping-cart"></i>
                </span>
                <span class="hide-menu">Quản lý đơn hàng</span>
              </a>
            </li>

            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Loại sản phẩm</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" asp-controller="Admin" asp-action="ViewLoaiSanPham" aria-expanded="false">
                <span>
                  <i class="ti ti-clothes-rack"></i>
                </span>
                <span class="hide-menu">Quản lý loại hàng</span>
              </a>
            </li>
          </ul>
        </nav>
        <!-- End Sidebar navigation -->
      </div>
      <!-- End Sidebar scroll-->
    </aside>
    <!--  Sidebar End -->
    <!--  Main wrapper -->
    <div class="body-wrapper">
      <!--  Header Start -->
      <header class="app-header">
        <nav class="navbar navbar-expand-lg navbar-light">
          <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
              <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                <i class="ti ti-menu-2"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                <i class="ti ti-bell-ringing"></i>
                <div class="notification bg-primary rounded-circle"></div>
              </a>
            </li>
          </ul>
          <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
              <li class="nav-item dropdown">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                   aria-expanded="false">
                  <img src="/assets_admin/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                  <div class="message-body">
                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-user fs-6"></i>
                      <p class="mb-0 fs-3">My Profile</p>
                    </a>
                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-mail fs-6"></i>
                      <p class="mb-0 fs-3">My Account</p>
                    </a>
                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-list-check fs-6"></i>
                      <p class="mb-0 fs-3">My Task</p>
                    </a>
                    <form id="logoutForm" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                      <button class="dropdown-item btn btn-outline-primary mx-3 mt-2 d-block" type="submit">Logout</button>
                    </form>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!--  Header End -->
      <!-- Body -->
      <div class="container-fluid">
        @RenderBody()
      </div>
      <!-- Body End -->

    </div>
  </div>

  <script>
    function Xoa(id, row) {
      // Store the ID of the item to be deleted in a variable
      var itemId = id;

      // Open a confirmation dialog using SweetAlert
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes'
      }).then((result) => {
        if (result.isConfirmed) {
          // If confirmed, send an AJAX request to delete the item
          $.ajax({
            url: `/Owner/Admin/Delete/${itemId}`,
            type: "POST",
            success: function (data) {
              // Remove the item from the DOM upon successful deletion
              row.closest("#box").remove();
              // Show a success message using SweetAlert
              Swal.fire(
                'Deleted!',
                'Your file has been deleted.',
                'success'
              )
            },
          })
        } else {
          // If cancelled, show a cancellation message using SweetAlert (optional)
          Swal.fire(
            'Cancelled',
            'Your action has been cancelled :)',
            'error'
          )
        }
      });
    }
  </script>

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js" integrity="sha512-L0Shl7nXXzIlBSUUPpxrokqq4ojqgZFQczTYlGjzONGTDAcLremjwaWv5A+EDLnxhQzY5xUZPWLOLqYRkY0Cbw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  
  <script src="~/assets_admin/libs/jquery/dist/jquery.min.js"></script>
  <script src="~/assets_admin/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets_admin/js/sidebarmenu.js"></script>
  <script src="~/assets_admin/js/app.min.js"></script>
  <script src="~/assets_admin/libs/apexcharts/dist/apexcharts.min.js"></script>
  <script src="~/assets_admin/libs/simplebar/dist/simplebar.js"></script>
  <script src="~/assets_admin/js/dashboard.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>